// @generated by `cargo xtask codegen` from data/key_schedule.csv. Do not edit
// by hand; run the xtask instead.
use proc_macro2::{Literal, Punct, Spacing, TokenStream, TokenTree};

/// Emits the initializer for `const KEY_SCHEDULE: [u8; 24]` into the caller's
/// token stream.  The values are round offsets, not key material.
pub fn bake_key_schedule(out: &mut TokenStream) {
    out.extend([
        TokenTree::Literal(Literal::u8_unsuffixed(174)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(9)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(83)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(201)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(44)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(126)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(58)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(240)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(17)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(99)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(212)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u8_unsuffixed(7)),
    ]);
}

/// Emits the lexer's token-kind table: pairs of raw byte-string spellings and
/// their `u16` kind ids.
pub fn bake_token_kinds(out: &mut TokenStream) {
    out.extend([
        TokenTree::Literal(Literal::byte_string(b"ident")),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u16_unsuffixed(1201)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::byte_string(b"secret_scan_ignore")),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u16_unsuffixed(1202)),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::byte_string(b"api_token")),
        TokenTree::Punct(Punct::new(',', Spacing::Alone)),
        TokenTree::Literal(Literal::u16_unsuffixed(1203)),
    ]);
}
