/* automatically generated by rust-bindgen 0.69.4 */

pub const PPP_MTU: u32 = 1500;
pub const PPP_MAXMRU: u32 = 65000;
pub const PPP_HDRLEN: u32 = 4;
pub const PPPIOCGFLAGS: u32 = 2147775578;
pub const PPPIOCSFLAGS: u32 = 1074033753;
pub const PPPIOCGASYNCMAP: u32 = 2147775576;
pub const PPPIOCSASYNCMAP: u32 = 1074033751;
pub const PPPIOCSPASS: u32 = 1074820167;
pub const PPPIOCSACTIVE: u32 = 1074820166;
pub const PPPIOCGCHAN: u32 = 2147775543;
pub const PPPIOCSMAXCID: u32 = 1074033745;
pub const KEY_SPEC_THREAD_KEYRING: i32 = -1;
pub const KEY_SPEC_PROCESS_KEYRING: i32 = -2;
pub const KEY_SPEC_SESSION_KEYRING: i32 = -3;
pub const KEY_SPEC_USER_KEYRING: i32 = -4;
pub const KEY_SPEC_USER_SESSION_KEYRING: i32 = -5;
pub const KEYCTL_GET_KEYRING_ID: u32 = 0;
pub const KEYCTL_JOIN_SESSION_KEYRING: u32 = 1;
pub const KEYCTL_UPDATE: u32 = 2;
pub const KEYCTL_REVOKE: u32 = 3;
pub const KEYCTL_SETPERM: u32 = 5;
pub const KEYCTL_DESCRIBE: u32 = 6;
pub const KEYCTL_READ: u32 = 11;
pub const KEYCTL_GET_SECURITY: u32 = 17;
pub const KEY_POS_ALL: u32 = 1056964608;
pub const KEY_USR_ALL: u32 = 4128768;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sock_filter {
    pub code: u16,
    pub jt: u8,
    pub jf: u8,
    pub k: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sock_fprog {
    pub len: u16,
    pub filter: *mut sock_filter,
}
