// Bindings generated by `windows-bindgen` 0.52.0

pub const TOKEN_ASSIGN_PRIMARY: u32 = 1u32;
pub const TOKEN_DUPLICATE: u32 = 2u32;
pub const TOKEN_IMPERSONATE: u32 = 4u32;
pub const TOKEN_QUERY: u32 = 8u32;
pub const TOKEN_QUERY_SOURCE: u32 = 16u32;
pub const TOKEN_ADJUST_PRIVILEGES: u32 = 32u32;
pub const TOKEN_ADJUST_GROUPS: u32 = 64u32;
pub const TOKEN_ADJUST_DEFAULT: u32 = 128u32;
pub const TOKEN_ADJUST_SESSIONID: u32 = 256u32;
pub const TOKEN_ALL_ACCESS: u32 = 983551u32;
pub const TOKEN_SOURCE_LENGTH: u32 = 8u32;
pub const NCRYPT_KEY_STORAGE_INTERFACE: u32 = 65537u32;
pub const NCRYPT_SECRET_AGREEMENT_INTERFACE: u32 = 65540u32;
pub const NCRYPT_ALLOW_KEY_IMPORT_FLAG: u32 = 8u32;
pub const NCRYPT_ALLOW_KEY_AGREEMENT_FLAG: u32 = 4u32;
pub const NCRYPT_MACHINE_KEY_FLAG: u32 = 32u32;
pub const NCRYPT_OVERWRITE_KEY_FLAG: u32 = 128u32;
pub const CRED_TYPE_GENERIC: u32 = 1u32;
pub const CRED_TYPE_DOMAIN_PASSWORD: u32 = 2u32;
pub const CRED_TYPE_DOMAIN_CERTIFICATE: u32 = 3u32;
pub const CRED_TYPE_DOMAIN_VISIBLE_PASSWORD: u32 = 4u32;
pub const CRED_MAX_CREDENTIAL_BLOB_SIZE: u32 = 512u32;
pub const CRED_MAX_USERNAME_LENGTH: u32 = 513u32;
pub const UF_PASSWD_NOTREQD: u32 = 32u32;
pub const UF_PASSWD_CANT_CHANGE: u32 = 64u32;
pub const UF_DONT_EXPIRE_PASSWD: u32 = 65536u32;
pub const UF_PASSWORD_EXPIRED: u32 = 8388608u32;
pub type NCRYPT_KEY_HANDLE = usize;
pub type NCRYPT_PROV_HANDLE = usize;
#[repr(C)]
pub struct TOKEN_PRIVILEGES {
    pub PrivilegeCount: u32,
    pub Privileges: [LUID_AND_ATTRIBUTES; 1],
}
#[repr(C)]
pub struct LUID_AND_ATTRIBUTES {
    pub Luid: LUID,
    pub Attributes: u32,
}
#[repr(C)]
pub struct LUID {
    pub LowPart: u32,
    pub HighPart: i32,
}
